version: '3'

services:
  todolistmysql:
    image: mysql:latest
    container_name: todolistmysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./MySQL:/var/lib/mysql